import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import "antd/dist/antd.css";

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>MobileKya</title>
        <meta name="mobile-kya" content="Generated by mobilekya" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};
export default Home;
